### ISSUE TITLE
Weird result

### ISSUE THREAD

**Issue by thibaultmol** [vabs/youtube-channel-name-converter#3]
I used the tool for a bit, but for some reason I got a weird result all of a sudden.
https://www.youtube.com/Silvervale
which results in
https://www.youtube.com/channel/UCfuGnJ6x-7uRQo-Ma5vwDQQ
according to the tool.
But the correct url should be
https://www.youtube.com/channel/UCm8Dj7dQ0oRHXNUXF31kjEw

**Comment by vabs** [comment]
@thibaultmol  The problem why the result is of a different channel, because youtube channel search take precedence over usernames than custom channel names which is a new functionality.

This is an existing bug in the youtube api and have been requested to be updated multiple time but Google has rejected it.

[Issue 1](https://issuetracker.google.com/issues/174903934)
[Issue 2](https://issuetracker.google.com/issues/165676622)
[Issue 3](https://issuetracker.google.com/issues/161718177)
